### ISSUE TITLE
can't load data?

### ISSUE THREAD

**Issue by songhat** [caglorithm/sleepy#1]
This error occurred when I used the data that came with mat file
![image](https://user-images.githubusercontent.com/48643755/221551978-7d531394-66d9-4863-95d3-b39560e2d9e1.png)

**Comment by songhat** [comment]
And I really want to know the .mat file. where exactly is it from , eeglab or fieldtrip?

**Comment by CristianaDim** [comment]
Hey, you need to make sure that you're using the matplotlib version specified in the requirements.txt file.

The data is from FieldTrip.
